apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
    - "grafana.192-168-56-240.nip.io"
  gateways:
    - istio-gateway
  http:
     - route:
        - destination:
            host: prometheus-grafana.monitoring.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager
  namespace: istio-system
spec:
  hosts:
    - "alertmanager.192-168-56-240.nip.io"
  gateways:
    - istio-gateway
  http:
     - route:
        - destination:
            host: prometheus-prometheus-oper-alertmanager.monitoring.svc.cluster.local
            port:
              number: 9093
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
    - "prometheus.192-168-56-240.nip.io"
  gateways:
    - istio-gateway
  http:
     - route:
        - destination:
            host: prometheus-prometheus-oper-prometheus.monitoring.svc.cluster.local
            port:
              number: 9090            
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - "kiali.192-168-56-240.nip.io"
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weave
  namespace: istio-system
spec:
  hosts:
    - "weave.192-168-56-240.nip.io"
  gateways:
    - istio-gateway
  http:
    - route:
        - destination:
            host: weave-scope-weave-scope.weave-scope.svc.cluster.local
            port:
              number: 80